/* ========================================================================
   预设模板数据（参考Wordly风格卡片颜色）
   - tint: 顶部色块背景色（马卡龙色系，不同主题不同色）
   - grade + wordCount: 次描述信息（Grades · N words）
   - emojis: 顶部两个大emoji图标（体现主题）
   - wordSets: 每个模板提供3组不同难度的词供选择
======================================================================== */
export type WordSet = {
  label: string // e.g. "Easy", "Medium", "Hard"
  words: string[]
}

export type PresetTemplate = {
  id: string
  slug: string
  title: string
  emoji1: string
  emoji2: string
  tint: string // tailwind / inline color
  grade: string // e.g. "Kindergarten", "Grades 1-2"
  wordCount: number // default word count (first set)
  wordSets: WordSet[] // 3 sets of words
  difficulty: "easy" | "medium" | "hard"
  category?: string // for grouping: "Animals", "Food", "Nature", "Science", "Geography", "Sports"
}

export const FEATURED_TEMPLATES: PresetTemplate[] = [
  {
    id: "animal-kingdom",
    slug: "animal-kingdom",
    title: "Animal Kingdom",
    emoji1: "🐘",
    emoji2: "🦋",
    tint: "#FCEEB8",
    grade: "Kindergarten",
    wordCount: 8,
    difficulty: "easy",
    wordSets: [
      { label: "Easy", words: ["cat", "dog", "fish", "bird", "fox"] },
      { label: "Medium", words: ["cat", "dog", "fish", "bird", "lion", "bear", "fox", "rabbit"] },
      { label: "Hard", words: ["cat", "dog", "fish", "bird", "lion", "bear", "fox", "rabbit", "elephant", "giraffe", "monkey", "cheetah", "kangaroo"] },
    ],
  },
  {
    id: "space-adventure",
    slug: "space-adventure",
    title: "Space Adventure",
    emoji1: "🚀",
    emoji2: "✨",
    tint: "#DCEBFA",
    grade: "Grades 3-4",
    wordCount: 10,
    difficulty: "medium",
    wordSets: [
      { label: "Easy", words: ["star", "moon", "mars", "comet", "orbit", "nasa"] },
      { label: "Medium", words: ["planet", "star", "rocket", "moon", "mars", "galaxy", "comet", "orbit", "nasa", "alien"] },
      { label: "Hard", words: ["planet", "star", "rocket", "moon", "mars", "galaxy", "comet", "orbit", "nasa", "alien", "telescope", "astronaut", "nebula", "satellite", "universe"] },
    ],
  },
  {
    id: "fruit-party",
    slug: "fruit-party",
    title: "Fruit Party",
    emoji1: "🍓",
    emoji2: "🍊",
    tint: "#E2EFDA",
    grade: "Grades 1-2",
    wordCount: 9,
    difficulty: "easy",
    wordSets: [
      { label: "Easy", words: ["apple", "grape", "peach", "lemon", "mango", "plum"] },
      { label: "Medium", words: ["apple", "banana", "grape", "melon", "peach", "lemon", "mango", "berry", "plum"] },
      { label: "Hard", words: ["apple", "banana", "grape", "melon", "peach", "lemon", "mango", "berry", "plum", "strawberry", "pineapple", "watermelon", "blueberry", "coconut"] },
    ],
  },
  {
    id: "ocean-friends",
    slug: "ocean-friends",
    title: "Ocean Friends",
    emoji1: "🐳",
    emoji2: "🐠",
    tint: "#DEF2F4",
    grade: "Grades 3-4",
    wordCount: 10,
    difficulty: "medium",
    wordSets: [
      { label: "Easy", words: ["shark", "coral", "whale", "seal", "crab"] },
      { label: "Medium", words: ["dolphin", "shark", "coral", "whale", "turtle", "octopus", "seal", "jellyfish", "crab", "starfish"] },
      { label: "Hard", words: ["dolphin", "shark", "coral", "whale", "turtle", "octopus", "seal", "jellyfish", "crab", "starfish", "swordfish", "seahorse", "barracuda", "lobster", "stingray"] },
    ],
  },
]

export const GRADE_TEMPLATES: PresetTemplate[] = [
  {
    id: "dolch-pre-k",
    slug: "dolch-pre-k",
    title: "Dolch Pre-K Sight Words",
    emoji1: "🔤",
    emoji2: "🧸",
    tint: "#FFE5E5",
    grade: "Pre-K",
    wordCount: 12,
    difficulty: "easy",
    wordSets: [
      { label: "Easy", words: ["a", "to", "is", "it", "in", "we", "up"] },
      { label: "Medium", words: ["and", "the", "a", "to", "is", "you", "it", "in", "my", "we", "go", "up"] },
      { label: "Hard", words: ["and", "the", "a", "to", "is", "you", "it", "in", "my", "we", "go", "up", "said", "look", "come", "down", "not"] },
    ],
  },
  {
    id: "dolch-kindergarten",
    slug: "dolch-kindergarten",
    title: "Dolch Kindergarten",
    emoji1: "🎒",
    emoji2: "✏️",
    tint: "#E6F2EE",
    grade: "Kindergarten",
    wordCount: 14,
    difficulty: "easy",
    wordSets: [
      { label: "Easy", words: ["am", "at", "be", "do", "he", "on", "can", "for"] },
      { label: "Medium", words: ["am", "are", "at", "be", "big", "can", "do", "for", "get", "have", "he", "like", "not", "on"] },
      { label: "Hard", words: ["am", "are", "at", "be", "big", "can", "do", "for", "get", "have", "he", "like", "not", "on", "must", "new", "now", "our", "out"] },
    ],
  },
  {
    id: "first-grade-basic",
    slug: "first-grade-basic",
    title: "1st Grade Spelling",
    emoji1: "📘",
    emoji2: "🌟",
    tint: "#FFF1DB",
    grade: "Grades 1",
    wordCount: 12,
    difficulty: "easy",
    wordSets: [
      { label: "Easy", words: ["an", "any", "as", "ask", "by", "day", "fly"] },
      { label: "Medium", words: ["after", "again", "an", "any", "as", "ask", "by", "could", "day", "every", "fly", "from"] },
      { label: "Hard", words: ["after", "again", "an", "any", "as", "ask", "by", "could", "day", "every", "fly", "from", "give", "going", "had", "has", "how"] },
    ],
  },
  {
    id: "second-grade-vocab",
    slug: "second-grade-vocab",
    title: "2nd Grade Vocabulary",
    emoji1: "📚",
    emoji2: "🏆",
    tint: "#E0EBFF",
    grade: "Grades 2",
    wordCount: 12,
    difficulty: "medium",
    wordSets: [
      { label: "Easy", words: ["best", "both", "buy", "call", "cold", "fast", "does"] },
      { label: "Medium", words: ["always", "around", "because", "before", "best", "both", "buy", "call", "cold", "does", "don't", "fast"] },
      { label: "Hard", words: ["always", "around", "because", "before", "best", "both", "buy", "call", "cold", "does", "don't", "fast", "found", "gave", "goes", "green", "many"] },
    ],
  },
]

export const THEME_TEMPLATES: PresetTemplate[] = [
  /* === ANIMALS === */
  {
    id: "dinosaurs",
    slug: "dinosaurs",
    title: "Dinosaurs Roar",
    emoji1: "🦖",
    emoji2: "🦕",
    tint: "#EBE5D6",
    grade: "Grades 2-3",
    wordCount: 9,
    difficulty: "medium",
    category: "Animals",
    wordSets: [
      { label: "Easy", words: ["trex", "bone", "egg", "fossil", "raptor"] },
      { label: "Medium", words: ["trex", "raptor", "fossil", "bone", "egg", "jurassic", "herbivore", "carnivore", "volcano"] },
      { label: "Hard", words: ["trex", "raptor", "fossil", "bone", "egg", "jurassic", "herbivore", "carnivore", "volcano", "stegosaurus", "triceratops", "paleontology", "brachiosaurus", "velociraptor"] },
    ],
  },
  {
    id: "farm-animals",
    slug: "farm-animals",
    title: "Farm Animals",
    emoji1: "🐄",
    emoji2: "🐓",
    tint: "#FFF3D6",
    grade: "Pre-K - K",
    wordCount: 10,
    difficulty: "easy",
    category: "Animals",
    wordSets: [
      { label: "Easy", words: ["cow", "pig", "duck", "goat", "barn", "sheep"] },
      { label: "Medium", words: ["cow", "pig", "horse", "sheep", "chicken", "duck", "goat", "barn", "tractor", "farmer"] },
      { label: "Hard", words: ["cow", "pig", "horse", "sheep", "chicken", "duck", "goat", "barn", "tractor", "farmer", "donkey", "rooster", "harvester", "scarecrow", "pasture"] },
    ],
  },
  {
    id: "pets",
    slug: "pets",
    title: "Pets at Home",
    emoji1: "🐶",
    emoji2: "🐱",
    tint: "#FFE5EC",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Animals",
    wordSets: [
      { label: "Easy", words: ["dog", "cat", "fish", "bird", "rabbit"] },
      { label: "Medium", words: ["dog", "cat", "fish", "hamster", "rabbit", "bird", "turtle", "parrot"] },
      { label: "Hard", words: ["dog", "cat", "fish", "hamster", "rabbit", "bird", "turtle", "parrot", "gerbil", "canary", "lizard", "ferret"] },
    ],
  },
  {
    id: "birds",
    slug: "birds",
    title: "Birds of a Feather",
    emoji1: "🦅",
    emoji2: "🦉",
    tint: "#E8F0D8",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Animals",
    wordSets: [
      { label: "Easy", words: ["owl", "hawk", "nest", "beak", "robin", "eagle"] },
      { label: "Medium", words: ["eagle", "sparrow", "robin", "owl", "hawk", "penguin", "parrot", "nest", "feather", "beak"] },
      { label: "Hard", words: ["eagle", "sparrow", "robin", "owl", "hawk", "penguin", "parrot", "nest", "feather", "beak", "flamingo", "peacock", "albatross", "woodpecker", "ostrich"] },
    ],
  },
  {
    id: "insects",
    slug: "insects",
    title: "Insect World",
    emoji1: "🐝",
    emoji2: "🦋",
    tint: "#FFF9C4",
    grade: "Grades 1-2",
    wordCount: 10,
    difficulty: "easy",
    category: "Animals",
    wordSets: [
      { label: "Easy", words: ["ant", "bee", "fly", "spider", "beetle", "ladybug"] },
      { label: "Medium", words: ["ant", "bee", "butterfly", "ladybug", "spider", "fly", "mosquito", "beetle", "grasshopper", "caterpillar"] },
      { label: "Hard", words: ["ant", "bee", "butterfly", "ladybug", "spider", "fly", "mosquito", "beetle", "grasshopper", "caterpillar", "dragonfly", "earthworm", "centipede", "scorpion"] },
    ],
  },
  {
    id: "zoo-animals",
    slug: "zoo-animals",
    title: "Zoo Adventures",
    emoji1: "🦁",
    emoji2: "🐘",
    tint: "#FFE0B2",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Animals",
    wordSets: [
      { label: "Easy", words: ["lion", "zebra", "tiger", "panda", "snake", "monkey"] },
      { label: "Medium", words: ["lion", "elephant", "giraffe", "zebra", "monkey", "tiger", "panda", "kangaroo", "snake", "gorilla"] },
      { label: "Hard", words: ["lion", "elephant", "giraffe", "zebra", "monkey", "tiger", "panda", "kangaroo", "snake", "gorilla", "hippopotamus", "rhinoceros", "crocodile", "chimpanzee", "leopard"] },
    ],
  },
  /* === FOOD === */
  {
    id: "food-snacks",
    slug: "food-snacks",
    title: "Yummy Food & Snacks",
    emoji1: "🍕",
    emoji2: "🍔",
    tint: "#FFE8D6",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Food",
    wordSets: [
      { label: "Easy", words: ["cake", "soup", "soda", "juice", "bread", "pizza"] },
      { label: "Medium", words: ["pizza", "burger", "cookie", "cake", "bread", "cheese", "salad", "soup", "soda", "juice"] },
      { label: "Hard", words: ["pizza", "burger", "cookie", "cake", "bread", "cheese", "salad", "soup", "soda", "juice", "sandwich", "spaghetti", "popcorn", "nachos", "pretzel"] },
    ],
  },
  {
    id: "vegetables",
    slug: "vegetables",
    title: "Garden Vegetables",
    emoji1: "🥕",
    emoji2: "🥦",
    tint: "#E8F5E1",
    grade: "Grades 1-2",
    wordCount: 10,
    difficulty: "easy",
    category: "Food",
    wordSets: [
      { label: "Easy", words: ["corn", "pea", "onion", "carrot", "potato", "pepper"] },
      { label: "Medium", words: ["carrot", "potato", "tomato", "broccoli", "onion", "pepper", "corn", "pea", "celery", "pumpkin"] },
      { label: "Hard", words: ["carrot", "potato", "tomato", "broccoli", "onion", "pepper", "corn", "pea", "celery", "pumpkin", "asparagus", "zucchini", "cauliflower", "artichoke", "spinach"] },
    ],
  },
  {
    id: "breakfast",
    slug: "breakfast",
    title: "Breakfast Time",
    emoji1: "🍳",
    emoji2: "🥞",
    tint: "#FFF8E1",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Food",
    wordSets: [
      { label: "Easy", words: ["egg", "milk", "toast", "juice", "bacon"] },
      { label: "Medium", words: ["egg", "toast", "milk", "cereal", "pancake", "waffle", "bacon", "juice"] },
      { label: "Hard", words: ["egg", "toast", "milk", "cereal", "pancake", "waffle", "bacon", "juice", "omelette", "sausage", "granola", "croissant", "muffin"] },
    ],
  },
  {
    id: "desserts",
    slug: "desserts",
    title: "Sweet Desserts",
    emoji1: "🍰",
    emoji2: "🍩",
    tint: "#FCE4EC",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Food",
    wordSets: [
      { label: "Easy", words: ["cake", "pie", "candy", "donut", "cookie"] },
      { label: "Medium", words: ["cake", "pie", "cookie", "donut", "brownie", "cupcake", "icecream", "pudding", "candy", "chocolate"] },
      { label: "Hard", words: ["cake", "pie", "cookie", "donut", "brownie", "cupcake", "icecream", "pudding", "candy", "chocolate", "tiramisu", "cheesecake", "macaroon", "strudel", "gelato"] },
    ],
  },
  /* === NATURE === */
  {
    id: "weather-sky",
    slug: "weather-sky",
    title: "Weather & Sky",
    emoji1: "☀️",
    emoji2: "🌧️",
    tint: "#DFF1FB",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Nature",
    wordSets: [
      { label: "Easy", words: ["snow", "wind", "fog", "rainy", "sunny", "storm"] },
      { label: "Medium", words: ["sunny", "cloudy", "rainy", "storm", "thunder", "snow", "wind", "rainbow", "fog", "tornado"] },
      { label: "Hard", words: ["sunny", "cloudy", "rainy", "storm", "thunder", "snow", "wind", "rainbow", "fog", "tornado", "blizzard", "lightning", "hurricane", "drought", "monsoon"] },
    ],
  },
  {
    id: "trees",
    slug: "trees",
    title: "Trees & Forests",
    emoji1: "🌳",
    emoji2: "🌲",
    tint: "#E0F0D5",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Nature",
    wordSets: [
      { label: "Easy", words: ["oak", "pine", "root", "leaf", "bark", "trunk"] },
      { label: "Medium", words: ["oak", "pine", "maple", "willow", "birch", "trunk", "root", "leaf", "branch", "bark"] },
      { label: "Hard", words: ["oak", "pine", "maple", "willow", "birch", "trunk", "root", "leaf", "branch", "bark", "redwood", "sequoia", "evergreen", "sapling", "canopy"] },
    ],
  },
  {
    id: "flowers",
    slug: "flowers",
    title: "Flowers in Bloom",
    emoji1: "🌹",
    emoji2: "🌻",
    tint: "#FCE4EC",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Nature",
    wordSets: [
      { label: "Easy", words: ["rose", "lily", "stem", "bloom", "tulip", "daisy"] },
      { label: "Medium", words: ["rose", "tulip", "daisy", "sunflower", "lily", "petal", "stem", "garden", "bloom", "pollen"] },
      { label: "Hard", words: ["rose", "tulip", "daisy", "sunflower", "lily", "petal", "stem", "garden", "bloom", "pollen", "orchid", "lavender", "chrysanthemum", "hibiscus", "magnolia"] },
    ],
  },
  {
    id: "mountains",
    slug: "mountains",
    title: "Mountains & Peaks",
    emoji1: "⛰️",
    emoji2: "🏔️",
    tint: "#E0E7EF",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Nature",
    wordSets: [
      { label: "Easy", words: ["peak", "trail", "cliff", "ridge", "valley", "canyon"] },
      { label: "Medium", words: ["peak", "ridge", "valley", "cliff", "boulder", "glacier", "trail", "summit", "avalanche", "canyon"] },
      { label: "Hard", words: ["peak", "ridge", "valley", "cliff", "boulder", "glacier", "trail", "summit", "avalanche", "canyon", "everest", "foothills", "crevasse", "precipice", "mountaineer"] },
    ],
  },
  /* === SCIENCE === */
  {
    id: "space-adventure",
    slug: "space-adventure-theme",
    title: "Space Adventure",
    emoji1: "🚀",
    emoji2: "🪐",
    tint: "#DCEBFA",
    grade: "Grades 3-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Science",
    wordSets: [
      { label: "Easy", words: ["star", "moon", "mars", "comet", "orbit", "nasa"] },
      { label: "Medium", words: ["planet", "star", "rocket", "moon", "mars", "galaxy", "comet", "orbit", "nasa", "alien"] },
      { label: "Hard", words: ["planet", "star", "rocket", "moon", "mars", "galaxy", "comet", "orbit", "nasa", "alien", "telescope", "astronaut", "nebula", "satellite", "universe"] },
    ],
  },
  {
    id: "human-body",
    slug: "human-body",
    title: "Human Body",
    emoji1: "🫀",
    emoji2: "🦴",
    tint: "#FFEBEE",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Science",
    wordSets: [
      { label: "Easy", words: ["lung", "heart", "brain", "blood", "liver", "nerve"] },
      { label: "Medium", words: ["heart", "brain", "lung", "liver", "stomach", "kidney", "muscle", "skeleton", "blood", "nerve"] },
      { label: "Hard", words: ["heart", "brain", "lung", "liver", "stomach", "kidney", "muscle", "skeleton", "blood", "nerve", "intestine", "artery", "cartilage", "pancreas", "vertebra"] },
    ],
  },
  {
    id: "chemistry",
    slug: "chemistry",
    title: "Chemistry Lab",
    emoji1: "⚗️",
    emoji2: "🧪",
    tint: "#E1F5FE",
    grade: "Grades 4-5",
    wordCount: 10,
    difficulty: "hard",
    category: "Science",
    wordSets: [
      { label: "Easy", words: ["atom", "acid", "base", "gas", "liquid", "element"] },
      { label: "Medium", words: ["atom", "molecule", "acid", "base", "reaction", "element", "compound", "mixture", "liquid", "gas"] },
      { label: "Hard", words: ["atom", "molecule", "acid", "base", "reaction", "element", "compound", "mixture", "liquid", "gas", "catalyst", "polymer", "isotope", "solution", "alkaline"] },
    ],
  },
  {
    id: "weather-science",
    slug: "weather-science",
    title: "Weather Science",
    emoji1: "🌡️",
    emoji2: "⚡",
    tint: "#E3F2FD",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Science",
    wordSets: [
      { label: "Easy", words: ["climate", "pressure", "forecast", "humidity", "barometer"] },
      { label: "Medium", words: ["temperature", "pressure", "humidity", "evaporation", "condensation", "precipitation", "climate", "forecast", "barometer", "humidity"] },
      { label: "Hard", words: ["temperature", "pressure", "humidity", "evaporation", "condensation", "precipitation", "climate", "forecast", "barometer", "humidity", "atmosphere", "meteorology", "thermometer", "stratosphere", "hygrometer"] },
    ],
  },
  /* === GEOGRAPHY === */
  {
    id: "continents",
    slug: "continents",
    title: "Continents & Oceans",
    emoji1: "🌍",
    emoji2: "🗺️",
    tint: "#E0F7FA",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Geography",
    wordSets: [
      { label: "Easy", words: ["asia", "africa", "europe", "arctic", "indian", "america"] },
      { label: "Medium", words: ["africa", "asia", "europe", "america", "australia", "antarctica", "pacific", "atlantic", "indian", "arctic"] },
      { label: "Hard", words: ["africa", "asia", "europe", "america", "australia", "antarctica", "pacific", "atlantic", "indian", "arctic", "eurasia", "hemisphere", "equator", "tropics", "greenland"] },
    ],
  },
  {
    id: "landforms",
    slug: "landforms",
    title: "Landforms",
    emoji1: "🌋",
    emoji2: "🏝️",
    tint: "#F1F8E9",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Geography",
    wordSets: [
      { label: "Easy", words: ["hill", "plain", "desert", "island", "valley", "canyon"] },
      { label: "Medium", words: ["mountain", "valley", "plateau", "canyon", "desert", "island", "peninsula", "plain", "hill", "volcano"] },
      { label: "Hard", words: ["mountain", "valley", "plateau", "canyon", "desert", "island", "peninsula", "plain", "hill", "volcano", "archipelago", "isthmus", "escarpment", "mesa", "fjord"] },
    ],
  },
  {
    id: "us-states",
    slug: "us-states",
    title: "US States",
    emoji1: "🗽",
    emoji2: "🏞️",
    tint: "#FFF3E0",
    grade: "Grades 4-5",
    wordCount: 12,
    difficulty: "hard",
    category: "Geography",
    wordSets: [
      { label: "Easy", words: ["ohio", "utah", "maine", "texas", "nevada", "oregon", "alaska"] },
      { label: "Medium", words: ["texas", "florida", "california", "oregon", "nevada", "montana", "maine", "vermont", "alaska", "hawaii", "ohio", "utah"] },
      { label: "Hard", words: ["texas", "florida", "california", "oregon", "nevada", "montana", "maine", "vermont", "alaska", "hawaii", "ohio", "utah", "massachusetts", "pennsylvania", "mississippi", "wisconsin", "connecticut"] },
    ],
  },
  {
    id: "world-capitals",
    slug: "world-capitals",
    title: "World Capitals",
    emoji1: "🏛️",
    emoji2: "🗼",
    tint: "#F3E5F5",
    grade: "Grades 4-5",
    wordCount: 10,
    difficulty: "hard",
    category: "Geography",
    wordSets: [
      { label: "Easy", words: ["rome", "paris", "tokyo", "delhi", "cairo", "madrid"] },
      { label: "Medium", words: ["paris", "london", "tokyo", "rome", "berlin", "madrid", "cairo", "beijing", "delhi", "canberra"] },
      { label: "Hard", words: ["paris", "london", "tokyo", "rome", "berlin", "madrid", "cairo", "beijing", "delhi", "canberra", "bucharest", "washington", "singapore", "stockholm", "edinburgh"] },
    ],
  },
  /* === SPORTS === */
  {
    id: "sports-games",
    slug: "sports-games",
    title: "Sports & Games",
    emoji1: "⚽",
    emoji2: "🏀",
    tint: "#E4F5E1",
    grade: "Grades 2-5",
    wordCount: 12,
    difficulty: "medium",
    category: "Sports",
    wordSets: [
      { label: "Easy", words: ["golf", "team", "coach", "match", "score", "rugby", "medal"] },
      { label: "Medium", words: ["soccer", "basketball", "tennis", "hockey", "rugby", "golf", "coach", "team", "score", "player", "medal", "match"] },
      { label: "Hard", words: ["soccer", "basketball", "tennis", "hockey", "rugby", "golf", "coach", "team", "score", "player", "medal", "match", "championship", "tournament", "quarterback", "goaltender", "referee"] },
    ],
  },
  {
    id: "basketball",
    slug: "basketball",
    title: "Basketball Stars",
    emoji1: "🏀",
    emoji2: "🏆",
    tint: "#FFF8E1",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Sports",
    wordSets: [
      { label: "Easy", words: ["pass", "hoop", "dunk", "court", "shoot", "three"] },
      { label: "Medium", words: ["dribble", "pass", "shoot", "rebound", "court", "hoop", "whistle", "referee", "dunk", "three"] },
      { label: "Hard", words: ["dribble", "pass", "shoot", "rebound", "court", "hoop", "whistle", "referee", "dunk", "three", "alleyoop", "fastbreak", "pointguard", "backboard", "turnover"] },
    ],
  },
  {
    id: "soccer",
    slug: "soccer",
    title: "Soccer Fever",
    emoji1: "⚽",
    emoji2: "🥅",
    tint: "#E8F5E1",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Sports",
    wordSets: [
      { label: "Easy", words: ["goal", "kick", "pass", "corner", "header", "whistle"] },
      { label: "Medium", words: ["goal", "kick", "pass", "keeper", "referee", "stadium", "whistle", "corner", "penalty", "header"] },
      { label: "Hard", words: ["goal", "kick", "pass", "keeper", "referee", "stadium", "whistle", "corner", "penalty", "header", "midfielder", "offside", "formation", "clearance", "defender"] },
    ],
  },
  {
    id: "olympics",
    slug: "olympics",
    title: "Olympic Games",
    emoji1: "🏅",
    emoji2: "🥇",
    tint: "#FFFDE7",
    grade: "Grades 3-5",
    wordCount: 10,
    difficulty: "medium",
    category: "Sports",
    wordSets: [
      { label: "Easy", words: ["gold", "medal", "torch", "silver", "running", "swimming"] },
      { label: "Medium", words: ["medal", "torch", "athlete", "stadium", "swimming", "running", "gymnastics", "ceremony", "gold", "silver"] },
      { label: "Hard", words: ["medal", "torch", "athlete", "stadium", "swimming", "running", "gymnastics", "ceremony", "gold", "silver", "decathlon", "podium", "marathon", "pentathlon", "badminton"] },
    ],
  },
  /* === ART === */
  {
    id: "drawing",
    slug: "drawing",
    title: "Drawing & Sketching",
    emoji1: "✏️",
    emoji2: "📝",
    tint: "#EDE4F7",
    grade: "Grades 1-3",
    wordCount: 8,
    difficulty: "easy",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["pen", "line", "draw", "paper", "pencil"] },
      { label: "Medium", words: ["pencil", "paper", "eraser", "crayon", "marker", "sketch", "drawing", "outline"] },
      { label: "Hard", words: ["pencil", "paper", "eraser", "crayon", "marker", "sketch", "drawing", "outline", "shading", "charcoal", "contour", "perspective", "hatching", "stippling"] },
    ],
  },
  {
    id: "painting",
    slug: "painting",
    title: "Painting Studio",
    emoji1: "🖌️",
    emoji2: "🎨",
    tint: "#FFE4F1",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["paint", "brush", "color", "canvas", "paper"] },
      { label: "Medium", words: ["paint", "brush", "canvas", "palette", "easel", "pigment", "watercolor", "acrylic", "tempera", "gouache"] },
      { label: "Hard", words: ["paint", "brush", "canvas", "palette", "easel", "pigment", "watercolor", "acrylic", "tempera", "gouache", "impasto", "glazing", "varnish", "brushstroke", "underpainting"] },
    ],
  },
  {
    id: "colors-art",
    slug: "colors-art",
    title: "Colors & Rainbows",
    emoji1: "🌈",
    emoji2: "🖍️",
    tint: "#FFF3E0",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["red", "blue", "pink", "gold", "green"] },
      { label: "Medium", words: ["red", "orange", "yellow", "green", "blue", "purple", "pink", "brown"] },
      { label: "Hard", words: ["red", "orange", "yellow", "green", "blue", "purple", "pink", "brown", "magenta", "turquoise", "lavender", "indigo", "violet", "crimson"] },
    ],
  },
  {
    id: "sculpture",
    slug: "sculpture",
    title: "Sculpture & Clay",
    emoji1: "🏺",
    emoji2: "🗿",
    tint: "#F5E6D3",
    grade: "Grades 2-4",
    wordCount: 9,
    difficulty: "medium",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["clay", "mold", "shape", "stone", "carve"] },
      { label: "Medium", words: ["clay", "mold", "shape", "stone", "carve", "sculpt", "marble", "bronze", "statue"] },
      { label: "Hard", words: ["clay", "mold", "shape", "stone", "carve", "sculpt", "marble", "bronze", "statue", "kiln", "ceramic", "relief", "patina", "assemblage"] },
    ],
  },
  {
    id: "pottery",
    slug: "pottery",
    title: "Pottery & Clay",
    emoji1: "🏺",
    emoji2: "👐",
    tint: "#EFEBE9",
    grade: "Grades 1-3",
    wordCount: 8,
    difficulty: "easy",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["clay", "pot", "mud", "bowl", "cup"] },
      { label: "Medium", words: ["clay", "pot", "bowl", "mug", "wheel", "kiln", "glaze", "throw"] },
      { label: "Hard", words: ["clay", "pot", "bowl", "mug", "wheel", "kiln", "glaze", "throw", "ceramic", "earthenware", "stoneware", "porcelain", "slipcast", "bisque"] },
    ],
  },
  {
    id: "collage",
    slug: "collage",
    title: "Collage & Cut Paper",
    emoji1: "✂️",
    emoji2: "📄",
    tint: "#FFF3E0",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["cut", "glue", "paper", "shape", "paste"] },
      { label: "Medium", words: ["cut", "glue", "paper", "shape", "paste", "scissors", "layer", "torn"] },
      { label: "Hard", words: ["cut", "glue", "paper", "shape", "paste", "scissors", "layer", "torn", "decoupage", "photomontage", "assemblage", "overlay", "composition", "texture"] },
    ],
  },
  {
    id: "printmaking",
    slug: "printmaking",
    title: "Printmaking Fun",
    emoji1: "🖨️",
    emoji2: "🎨",
    tint: "#E1F5FE",
    grade: "Grades 2-4",
    wordCount: 9,
    difficulty: "medium",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["print", "stamp", "ink", "press", "paper"] },
      { label: "Medium", words: ["print", "stamp", "ink", "press", "paper", "plate", "roller", "etch", "block"] },
      { label: "Hard", words: ["print", "stamp", "ink", "press", "paper", "plate", "roller", "etch", "block", "intaglio", "relief", "lithography", "edition", "monoprint", "engraving"] },
    ],
  },
  {
    id: "palette",
    slug: "palette",
    title: "Artist Palette",
    emoji1: "🎨",
    emoji2: "🖌️",
    tint: "#FCE4EC",
    grade: "Grades 1-3",
    wordCount: 8,
    difficulty: "easy",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["red", "blue", "mix", "paint", "color"] },
      { label: "Medium", words: ["palette", "mix", "paint", "color", "hue", "tint", "shade", "swatch"] },
      { label: "Hard", words: ["palette", "mix", "paint", "color", "hue", "tint", "shade", "swatch", "pigment", "primary", "secondary", "complementary", "gradient", "saturation"] },
    ],
  },
  {
    id: "easel",
    slug: "easel",
    title: "Easel & Studio",
    emoji1: "🖼️",
    emoji2: "🎨",
    tint: "#FFF8E1",
    grade: "Grades 1-3",
    wordCount: 8,
    difficulty: "easy",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["easel", "stand", "paint", "canvas", "art"] },
      { label: "Medium", words: ["easel", "stand", "canvas", "paint", "studio", "tripod", "mast", "clamp"] },
      { label: "Hard", words: ["easel", "stand", "canvas", "paint", "studio", "tripod", "mast", "clamp", "tilting", "sketchbox", "display", "adjustable", "field", "portable"] },
    ],
  },
  {
    id: "digital-art",
    slug: "digital-art",
    title: "Digital Art",
    emoji1: "💻",
    emoji2: "✨",
    tint: "#E8EAF6",
    grade: "Grades 2-4",
    wordCount: 9,
    difficulty: "medium",
    category: "Art",
    wordSets: [
      { label: "Easy", words: ["draw", "screen", "pen", "color", "tablet"] },
      { label: "Medium", words: ["digital", "layer", "brush", "tablet", "stylus", "screen", "color", "pixel", "vector"] },
      { label: "Hard", words: ["digital", "layer", "brush", "tablet", "stylus", "screen", "color", "pixel", "vector", "bezier", "raster", "mask", "gradient", "opacity", "render"] },
    ],
  },
  /* === SHOPPING === */
  {
    id: "supermarket",
    slug: "supermarket",
    title: "Supermarket Trip",
    emoji1: "🛒",
    emoji2: "🥬",
    tint: "#E8F5E9",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["cart", "shop", "milk", "bread", "eggs", "fruit"] },
      { label: "Medium", words: ["cart", "aisle", "checkout", "grocery", "produce", "dairy", "frozen", "sale", "receipt", "shelf"] },
      { label: "Hard", words: ["cart", "aisle", "checkout", "grocery", "produce", "dairy", "frozen", "sale", "receipt", "shelf", "delicatessen", "bakery", "butcher", "coupon", "barcode"] },
    ],
  },
  {
    id: "store",
    slug: "store",
    title: "At the Store",
    emoji1: "🏪",
    emoji2: "📦",
    tint: "#FFF8E1",
    grade: "Grades 1-2",
    wordCount: 8,
    difficulty: "easy",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["shop", "buy", "bag", "cash", "store", "sell"] },
      { label: "Medium", words: ["store", "shop", "buy", "sell", "price", "money", "bag", "cashier", "customer", "register"] },
      { label: "Hard", words: ["store", "shop", "buy", "sell", "price", "money", "bag", "cashier", "customer", "register", "inventory", "merchandise", "display", "purchase", "transaction"] },
    ],
  },
  {
    id: "checkout",
    slug: "checkout",
    title: "Checkout Time",
    emoji1: "💳",
    emoji2: "🧾",
    tint: "#E3F2FD",
    grade: "Grades 2-3",
    wordCount: 9,
    difficulty: "medium",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["pay", "cash", "card", "bag", "change"] },
      { label: "Medium", words: ["checkout", "scanner", "payment", "receipt", "cashier", "bag", "change", "total", "card", "cash"] },
      { label: "Hard", words: ["checkout", "scanner", "payment", "receipt", "cashier", "bag", "change", "total", "card", "cash", "barcode", "kiosk", "tender", "void", "subtotal"] },
    ],
  },
  {
    id: "coupons",
    slug: "coupons",
    title: "Coupons & Sales",
    emoji1: "🏷️",
    emoji2: "💰",
    tint: "#FCE4EC",
    grade: "Grades 2-4",
    wordCount: 9,
    difficulty: "medium",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["sale", "save", "deal", "price", "off"] },
      { label: "Medium", words: ["coupon", "sale", "save", "deal", "price", "discount", "offer", "promo", "bargain", "clearance"] },
      { label: "Hard", words: ["coupon", "sale", "save", "deal", "price", "discount", "offer", "promo", "bargain", "clearance", "redemption", "markdown", "flyer", "rebate", "voucher"] },
    ],
  },
  {
    id: "online-shopping",
    slug: "online-shopping",
    title: "Online Shopping",
    emoji1: "💻",
    emoji2: "📦",
    tint: "#E8EAF6",
    grade: "Grades 2-4",
    wordCount: 9,
    difficulty: "medium",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["cart", "buy", "online", "order", "ship"] },
      { label: "Medium", words: ["online", "cart", "checkout", "order", "ship", "track", "delivery", "payment", "account"] },
      { label: "Hard", words: ["online", "cart", "checkout", "order", "ship", "track", "delivery", "payment", "account", "fulfillment", "subscription", "wishlist", "tracking", "courier", "logistics"] },
    ],
  },
  {
    id: "cart",
    slug: "cart",
    title: "Shopping Cart",
    emoji1: "🛒",
    emoji2: "🥕",
    tint: "#F1F8E9",
    grade: "Pre-K - K",
    wordCount: 10,
    difficulty: "easy",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["cart", "push", "wheel", "food", "bag"] },
      { label: "Medium", words: ["cart", "push", "wheel", "basket", "trolley", "food", "bag", "load", "roll", "carry"] },
      { label: "Hard", words: ["cart", "push", "wheel", "basket", "trolley", "food", "bag", "load", "roll", "carry", "corral", "nesting", "handlebar", "coinlock", "steerable"] },
    ],
  },
  {
    id: "aisle",
    slug: "aisle",
    title: "Store Aisles",
    emoji1: "🛍️",
    emoji2: "🏷️",
    tint: "#FFF3E0",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["aisle", "shelf", "walk", "find", "look"] },
      { label: "Medium", words: ["aisle", "shelf", "walk", "find", "look", "sign", "section", "row", "display", "endcap"] },
      { label: "Hard", words: ["aisle", "shelf", "walk", "find", "look", "sign", "section", "row", "display", "endcap", "planogram", "gondola", "facing", "merchandise", "fixture"] },
    ],
  },
  {
    id: "delivery-tracking",
    slug: "delivery-tracking",
    title: "Delivery Tracking",
    emoji1: "🚚",
    emoji2: "📍",
    tint: "#E3F2FD",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["box", "truck", "ship", "send", "bring"] },
      { label: "Medium", words: ["delivery", "truck", "ship", "box", "track", "package", "route", "driver", "send", "arrive"] },
      { label: "Hard", words: ["delivery", "truck", "ship", "box", "track", "package", "route", "driver", "send", "arrive", "carrier", "scan", "hub", "lastmile", "dispatch"] },
    ],
  },
  {
    id: "self-checkout",
    slug: "self-checkout",
    title: "Self-Checkout",
    emoji1: "🤖",
    emoji2: "🛒",
    tint: "#F3E5F5",
    grade: "Grades 2-3",
    wordCount: 10,
    difficulty: "medium",
    category: "Shopping",
    wordSets: [
      { label: "Easy", words: ["scan", "beep", "bag", "pay", "screen"] },
      { label: "Medium", words: ["selfcheckout", "scan", "beep", "bag", "pay", "screen", "scale", "kiosk", "card", "cash"] },
      { label: "Hard", words: ["selfcheckout", "scan", "beep", "bag", "pay", "screen", "scale", "kiosk", "card", "cash", "lookup", "attendant", "override", "prompt", "terminal"] },
    ],
  },
  /* === FAMILY === */
  {
    id: "family-members",
    slug: "family-members",
    title: "Family Members",
    emoji1: "👨‍👩‍👧",
    emoji2: "👶",
    tint: "#FFE0B2",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["mom", "dad", "sister", "baby", "brother"] },
      { label: "Medium", words: ["mother", "father", "sister", "brother", "grandma", "grandpa", "baby", "aunt", "uncle", "cousin"] },
      { label: "Hard", words: ["mother", "father", "sister", "brother", "grandmother", "grandfather", "grandma", "grandpa", "aunt", "uncle", "cousin", "niece", "nephew", "daughter", "son"] },
    ],
  },
  {
    id: "friends",
    slug: "friends",
    title: "Best Friends",
    emoji1: "🤝",
    emoji2: "😄",
    tint: "#E1F5FE",
    grade: "Grades 1-2",
    wordCount: 8,
    difficulty: "easy",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["friend", "play", "share", "fun", "smile"] },
      { label: "Medium", words: ["friend", "play", "share", "smile", "trust", "kindness", "together", "laugh", "help", "care"] },
      { label: "Hard", words: ["friendship", "playground", "together", "kindness", "trust", "companion", "support", "loyalty", "laughter", "bonding", "respect", "honesty", "teamwork", "caring"] },
    ],
  },
  {
    id: "cousins",
    slug: "cousins",
    title: "Cousins & Kin",
    emoji1: "🧒",
    emoji2: "👧",
    tint: "#F3E5F5",
    grade: "Grades 1-3",
    wordCount: 9,
    difficulty: "medium",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["cousin", "aunt", "uncle", "visit", "family"] },
      { label: "Medium", words: ["cousin", "aunt", "uncle", "family", "visit", "reunion", "relative", "kin", "gather", "play"] },
      { label: "Hard", words: ["cousin", "aunt", "uncle", "family", "visit", "reunion", "relative", "kin", "gather", "play", "nephew", "niece", "siblings", "ancestry", "heritage"] },
    ],
  },
  {
    id: "wedding",
    slug: "wedding",
    title: "Wedding Celebration",
    emoji1: "💒",
    emoji2: "💐",
    tint: "#FCE4EC",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["bride", "groom", "cake", "ring", "love", "party"] },
      { label: "Medium", words: ["bride", "groom", "wedding", "cake", "ring", "flower", "dress", "suit", "vows", "party"] },
      { label: "Hard", words: ["bride", "groom", "wedding", "cake", "ring", "flower", "dress", "suit", "vows", "party", "ceremony", "reception", "bouquet", "honeymoon", "bridesmaid"] },
    ],
  },
  {
    id: "babies",
    slug: "babies",
    title: "Babies & Toddlers",
    emoji1: "👶",
    emoji2: "🍼",
    tint: "#FFE0B2",
    grade: "Pre-K - K",
    wordCount: 10,
    difficulty: "easy",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["baby", "milk", "cry", "toy", "nap"] },
      { label: "Medium", words: ["baby", "bottle", "milk", "cry", "toy", "nap", "bib", "crib", "stroller", "blanket"] },
      { label: "Hard", words: ["baby", "bottle", "milk", "cry", "toy", "nap", "bib", "crib", "stroller", "blanket", "newborn", "toddler", "pacifier", "diaper", "lullaby"] },
    ],
  },
  {
    id: "neighbors",
    slug: "neighbors",
    title: "Neighbors & Block",
    emoji1: "🏠",
    emoji2: "👋",
    tint: "#E8F5E9",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["next", "door", "home", "wave", "hello"] },
      { label: "Medium", words: ["neighbor", "door", "home", "wave", "hello", "block", "street", "friendly", "greet", "nearby"] },
      { label: "Hard", words: ["neighbor", "door", "home", "wave", "hello", "block", "street", "friendly", "greet", "nearby", "courtesy", "doorstep", "community", "suburban", "hometown"] },
    ],
  },
  {
    id: "community",
    slug: "community",
    title: "Community Helpers",
    emoji1: "👩‍🚒",
    emoji2: "👨‍🌾",
    tint: "#E1F5FE",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["help", "town", "fire", "mail", "care"] },
      { label: "Medium", words: ["community", "helper", "firefighter", "police", "mail", "doctor", "teacher", "farmer", "nurse", "volunteer"] },
      { label: "Hard", words: ["community", "helper", "firefighter", "police", "mail", "doctor", "teacher", "farmer", "nurse", "volunteer", "librarian", "paramedic", "carpenter", "leadership", "service"] },
    ],
  },
  {
    id: "reunion",
    slug: "reunion",
    title: "Family Reunion",
    emoji1: "🎉",
    emoji2: "👨‍👩‍👧‍👦",
    tint: "#FCE4EC",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "medium",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["meet", "hug", "eat", "play", "family"] },
      { label: "Medium", words: ["reunion", "meet", "hug", "eat", "play", "family", "gather", "party", "travel", "photo"] },
      { label: "Hard", words: ["reunion", "meet", "hug", "eat", "play", "family", "gather", "party", "travel", "photo", "celebration", "memory", "tradition", "welcome", "together"] },
    ],
  },
  {
    id: "family-traditions",
    slug: "family-traditions",
    title: "Family Traditions",
    emoji1: "🎄",
    emoji2: "🎂",
    tint: "#FFF8E1",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Family",
    wordSets: [
      { label: "Easy", words: ["tradition", "story", "recipe", "song", "game"] },
      { label: "Medium", words: ["tradition", "story", "recipe", "song", "game", "holiday", "birthday", "dinner", "memory", "celebrate"] },
      { label: "Hard", words: ["tradition", "story", "recipe", "song", "game", "holiday", "birthday", "dinner", "memory", "celebrate", "heritage", "ritual", "keepsake", "custom", "legacy"] },
    ],
  },
  /* === EMOTIONS === */
  {
    id: "feelings",
    slug: "feelings",
    title: "Feelings & Moods",
    emoji1: "😊",
    emoji2: "😢",
    tint: "#FFF9C4",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["happy", "sad", "mad", "glad", "scared"] },
      { label: "Medium", words: ["happy", "sad", "angry", "scared", "silly", "excited", "tired", "proud", "shy", "brave"] },
      { label: "Hard", words: ["happy", "sad", "angry", "scared", "silly", "excited", "tired", "proud", "shy", "brave", "nervous", "grateful", "curious", "confused", "surprised"] },
    ],
  },
  {
    id: "happiness",
    slug: "happiness",
    title: "Happiness & Joy",
    emoji1: "😄",
    emoji2: "🌈",
    tint: "#FFFDE7",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["joy", "smile", "laugh", "fun", "glad"] },
      { label: "Medium", words: ["joy", "smile", "laugh", "happy", "fun", "glad", "cheer", "delight", "giggle", "celebrate"] },
      { label: "Hard", words: ["joy", "smile", "laugh", "happy", "fun", "glad", "cheer", "delight", "giggle", "celebrate", "gratitude", "blissful", "jubilation", "contentment", "festivity"] },
    ],
  },
  {
    id: "confidence",
    slug: "confidence",
    title: "Confidence & Courage",
    emoji1: "💪",
    emoji2: "🦁",
    tint: "#E8F5E9",
    grade: "Grades 2-4",
    wordCount: 9,
    difficulty: "medium",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["brave", "strong", "proud", "bold", "try"] },
      { label: "Medium", words: ["brave", "strong", "proud", "bold", "confident", "courage", "fearless", "hero", "try", "win"] },
      { label: "Hard", words: ["brave", "strong", "proud", "bold", "confident", "courage", "fearless", "hero", "try", "win", "determined", "fearlessness", "resilient", "steadfast", "empowered"] },
    ],
  },
  {
    id: "patience",
    slug: "patience",
    title: "Patience & Calm",
    emoji1: "🧘",
    emoji2: "🐢",
    tint: "#E1F5FE",
    grade: "Grades 1-3",
    wordCount: 8,
    difficulty: "easy",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["wait", "calm", "slow", "breathe", "rest"] },
      { label: "Medium", words: ["wait", "calm", "slow", "breathe", "rest", "gentle", "steady", "quiet", "peace", "still"] },
      { label: "Hard", words: ["patience", "waiting", "peaceful", "steadiness", "composure", "gentleness", "tranquility", "stillness", "endurance", "calmness", "serenity", "mindfulness", "forbearance"] },
    ],
  },
  {
    id: "gratitude",
    slug: "gratitude",
    title: "Gratitude & Thanks",
    emoji1: "🙏",
    emoji2: "💛",
    tint: "#FFFDE7",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["thanks", "kind", "glad", "help", "gift"] },
      { label: "Medium", words: ["thanks", "kind", "glad", "help", "gift", "grateful", "appreciate", "blessed", "give", "share"] },
      { label: "Hard", words: ["thanks", "kind", "glad", "help", "gift", "grateful", "appreciate", "blessed", "give", "share", "thankful", "kindness", "generosity", "blessing", "appreciation"] },
    ],
  },
  {
    id: "empathy",
    slug: "empathy",
    title: "Empathy & Caring",
    emoji1: "🤗",
    emoji2: "💖",
    tint: "#FCE4EC",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["care", "hug", "kind", "help", "love"] },
      { label: "Medium", words: ["care", "hug", "kind", "help", "love", "empathy", "listen", "comfort", "share", "understand"] },
      { label: "Hard", words: ["care", "hug", "kind", "help", "love", "empathy", "listen", "comfort", "share", "understand", "compassion", "kindness", "warmth", "support", "gentleness"] },
    ],
  },
  {
    id: "curiosity",
    slug: "curiosity",
    title: "Curiosity & Wonder",
    emoji1: "🤔",
    emoji2: "🔍",
    tint: "#E8EAF6",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["ask", "why", "look", "find", "new"] },
      { label: "Medium", words: ["ask", "why", "look", "find", "new", "curious", "wonder", "explore", "question", "learn"] },
      { label: "Hard", words: ["ask", "why", "look", "find", "new", "curious", "wonder", "explore", "question", "learn", "discovery", "inquire", "investigate", "fascinate", "intrigue"] },
    ],
  },
  {
    id: "resilience",
    slug: "resilience",
    title: "Resilience & Bounce",
    emoji1: "🌟",
    emoji2: "💪",
    tint: "#E8F5E9",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["try", "again", "strong", "brave", "ok"] },
      { label: "Medium", words: ["try", "again", "strong", "brave", "ok", "bounce", "recover", "grit", "keep", "grow"] },
      { label: "Hard", words: ["try", "again", "strong", "brave", "ok", "bounce", "recover", "grit", "keep", "grow", "resilience", "persevere", "determined", "steadfast", "courage"] },
    ],
  },
  {
    id: "personality",
    slug: "personality",
    title: "Personality Words",
    emoji1: "😊",
    emoji2: "🦋",
    tint: "#F3E5F5",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Emotions",
    wordSets: [
      { label: "Easy", words: ["kind", "fun", "shy", "loud", "nice"] },
      { label: "Medium", words: ["kind", "fun", "shy", "loud", "nice", "brave", "funny", "quiet", "gentle", "smart"] },
      { label: "Hard", words: ["kind", "fun", "shy", "loud", "nice", "brave", "funny", "quiet", "gentle", "smart", "curious", "creative", "honest", "cheerful", "thoughtful"] },
    ],
  },
  /* === CLOTHES === */
  {
    id: "tops",
    slug: "tops",
    title: "Tops & Shirts",
    emoji1: "👕",
    emoji2: "👚",
    tint: "#E3F2FD",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["shirt", "hat", "coat", "vest", "hood"] },
      { label: "Medium", words: ["shirt", "sweater", "jacket", "hoodie", "tshirt", "blouse", "vest", "coat", "cardigan", "pullover"] },
      { label: "Hard", words: ["shirt", "sweater", "jacket", "hoodie", "tshirt", "blouse", "vest", "coat", "cardigan", "pullover", "sweatshirt", "windbreaker", "turtleneck", "tanktop", "buttondown"] },
    ],
  },
  {
    id: "pants",
    slug: "pants",
    title: "Pants & Bottoms",
    emoji1: "👖",
    emoji2: "🩳",
    tint: "#FFF3E0",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["pants", "jeans", "shorts", "long", "leg"] },
      { label: "Medium", words: ["pants", "jeans", "shorts", "trousers", "leggings", "skirt", "sweatpants", "overalls", "khaki", "cargo"] },
      { label: "Hard", words: ["pants", "jeans", "shorts", "trousers", "leggings", "skirt", "sweatpants", "overalls", "khaki", "cargo", "corduroy", "denim", "drawstring", "waistband", "hemline"] },
    ],
  },
  {
    id: "shoes",
    slug: "shoes",
    title: "Shoes & Sneakers",
    emoji1: "👟",
    emoji2: "👢",
    tint: "#FCE4EC",
    grade: "Pre-K - K",
    wordCount: 8,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["shoe", "sock", "boot", "lace", "foot"] },
      { label: "Medium", words: ["shoes", "sneakers", "boots", "sandals", "socks", "laces", "slippers", "heels", "flats", "loafers"] },
      { label: "Hard", words: ["sneakers", "boots", "sandals", "slippers", "loafers", "oxfords", "cleats", "flipflops", "espadrilles", "moccasins", "galoshes", "brogues", "stilettos", "slingbacks"] },
    ],
  },
  {
    id: "accessories",
    slug: "accessories",
    title: "Accessories & Extras",
    emoji1: "🎩",
    emoji2: "👜",
    tint: "#F3E5F5",
    grade: "Grades 1-3",
    wordCount: 9,
    difficulty: "medium",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["hat", "bag", "belt", "watch", "ring"] },
      { label: "Medium", words: ["hat", "scarf", "gloves", "belt", "watch", "bag", "necklace", "ring", "bracelet", "earrings"] },
      { label: "Hard", words: ["hat", "scarf", "gloves", "belt", "watch", "handbag", "necklace", "bracelet", "earrings", "sunglasses", "headband", "brooch", "pendant", "anklet", "headwear"] },
    ],
  },
  {
    id: "seasonal-clothes",
    slug: "seasonal-clothes",
    title: "Seasonal Clothes",
    emoji1: "🧥",
    emoji2: "🩱",
    tint: "#E1F5FE",
    grade: "Pre-K - K",
    wordCount: 10,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["coat", "hat", "mittens", "boots", "sun"] },
      { label: "Medium", words: ["coat", "hat", "mittens", "boots", "swimsuit", "jacket", "sandals", "scarf", "sunglasses", "raincoat"] },
      { label: "Hard", words: ["coat", "hat", "mittens", "boots", "swimsuit", "jacket", "sandals", "scarf", "sunglasses", "raincoat", "snowsuit", "windbreaker", "sundress", "galoshes", "thermals"] },
    ],
  },
  {
    id: "washing-clothes",
    slug: "washing-clothes",
    title: "Washing Clothes",
    emoji1: "🧺",
    emoji2: "🧼",
    tint: "#E8F5E9",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["wash", "soap", "water", "dry", "fold"] },
      { label: "Medium", words: ["wash", "soap", "water", "dry", "fold", "basket", "machine", "detergent", "hang", "iron"] },
      { label: "Hard", words: ["wash", "soap", "water", "dry", "fold", "basket", "machine", "detergent", "hang", "iron", "bleach", "rinse", "stain", "softener", "dryer"] },
    ],
  },
  {
    id: "fabric",
    slug: "fabric",
    title: "Fabric & Textiles",
    emoji1: "🧵",
    emoji2: "🧶",
    tint: "#EFEBE9",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["soft", "cotton", "wool", "silk", "cloth"] },
      { label: "Medium", words: ["cotton", "wool", "silk", "cloth", "linen", "denim", "fleece", "leather", "velvet", "knit"] },
      { label: "Hard", words: ["cotton", "wool", "silk", "cloth", "linen", "denim", "fleece", "leather", "velvet", "knit", "polyester", "cashmere", "satin", "flannel", "terrycloth"] },
    ],
  },
  {
    id: "layer",
    slug: "layer",
    title: "Layering Clothes",
    emoji1: "🧥",
    emoji2: "👕",
    tint: "#FFF3E0",
    grade: "Grades 1-3",
    wordCount: 10,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["shirt", "coat", "warm", "cold", "wear"] },
      { label: "Medium", words: ["shirt", "coat", "warm", "cold", "wear", "layer", "sweater", "vest", "jacket", "hoodie"] },
      { label: "Hard", words: ["shirt", "coat", "warm", "cold", "wear", "layer", "sweater", "vest", "jacket", "hoodie", "baselayer", "midlayer", "shell", "insulation", "thermals"] },
    ],
  },
  {
    id: "casual-wear",
    slug: "casual-wear",
    title: "Casual & Play Wear",
    emoji1: "👕",
    emoji2: "🩳",
    tint: "#F1F8E9",
    grade: "Pre-K - K",
    wordCount: 10,
    difficulty: "easy",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["tshirt", "jeans", "shorts", "sneakers", "cap"] },
      { label: "Medium", words: ["tshirt", "jeans", "shorts", "sneakers", "hoodie", "cap", "sweatpants", "tanktop", "flipflops", "leggings"] },
      { label: "Hard", words: ["tshirt", "jeans", "shorts", "sneakers", "hoodie", "cap", "sweatpants", "tanktop", "flipflops", "leggings", "athleisure", "streetwear", "denim", "joggers", "windbreaker"] },
    ],
  },
  {
    id: "formal-wear",
    slug: "formal-wear",
    title: "Dress-Up & Formal",
    emoji1: "👔",
    emoji2: "👗",
    tint: "#FCE4EC",
    grade: "Grades 2-4",
    wordCount: 10,
    difficulty: "medium",
    category: "Clothes",
    wordSets: [
      { label: "Easy", words: ["dress", "suit", "tie", "shoes", "shirt"] },
      { label: "Medium", words: ["dress", "suit", "tie", "shoes", "shirt", "gown", "tuxedo", "bowtie", "skirt", "blazer"] },
      { label: "Hard", words: ["dress", "suit", "tie", "shoes", "shirt", "gown", "tuxedo", "bowtie", "skirt", "blazer", "cummerbund", "waistcoat", "lapel", "boutonniere", "train"] },
    ],
  },
]
