import type { Metadata } from "next"
import { FileText, Mail } from "lucide-react"
import { PageLayout } from "@/components/layout/PageLayout"
import { Button } from "@/components/ui/button"

export const metadata: Metadata = {
  title: "Terms of Service - Word Puzzle Generator",
  description:
    "The terms and conditions for using Word Puzzle Generator, including acceptable use, account responsibilities, intellectual property, and subscription terms.",
}

const SECTIONS = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    body: [
      "By accessing or using Word Puzzle Generator (the &ldquo;Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.",
      "These terms apply to all visitors, registered users, and subscribers. If you are using the Service on behalf of a school or organization, you represent that you have authority to bind that entity.",
    ],
  },
  {
    id: "description",
    title: "2. Description of Service",
    body: [
      "Word Puzzle Generator is a web-based tool that lets users create, customize, save, and print word search puzzles for educational and personal use.",
      "We offer a free plan with limited monthly credits, and paid subscription plans (Basic and Pro) with additional features. Plan details and pricing are listed on our Pricing page.",
    ],
  },
  {
    id: "accounts",
    title: "3. Accounts & Responsibilities",
    body: [
      "You must be at least 13 years old (or have parent/guardian consent) to create an account.",
      "You are responsible for keeping your password secure and for all activity that happens under your account.",
      "You agree to notify us immediately of any unauthorized use of your account or any other security breach.",
      "We may suspend or terminate accounts that violate these terms or engage in fraudulent, abusive, or unlawful activity.",
    ],
  },
  {
    id: "acceptable-use",
    title: "4. Acceptable Use",
    body: [
      "You agree NOT to use the Service to:",
      "Generate puzzles containing content that is unlawful, defamatory, harassing, hateful, or infringes on someone else's intellectual property.",
      "Attempt to reverse-engineer, scrape, or overload the Service or its underlying systems.",
      "Use automated scripts, bots, or crawlers to access the Service in a way that exceeds normal human usage.",
      "Resell, sublicense, or redistribute access to the Service without our written permission.",
    ],
  },
  {
    id: "ip",
    title: "5. Intellectual Property",
    body: [
      "Puzzles you create with the Service belong to you. You are free to print, share, and use them in your classroom, home, or other non-commercial educational settings.",
      "The Service itself — including the website design, template artwork, code, and brand — is owned by Word Puzzle Generator and protected by copyright and trademark law.",
      "You may not copy, modify, or distribute our code, branding, or template designs without written permission.",
    ],
  },
  {
    id: "subscriptions",
    title: "6. Subscriptions & Billing",
    body: [
      "Paid plans are billed in advance on a monthly or annual basis, depending on the plan you select.",
      "Payments are processed securely by our payment provider (Stripe). We never see or store your full card number.",
      "You can cancel your subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period — no further charges will be made.",
      "Refunds are handled on a case-by-case basis. If you are unhappy with the Service, contact us and we will do our best to make it right.",
    ],
  },
  {
    id: "free-credits",
    title: "7. Credits & Usage Limits",
    body: [
      "Each puzzle generation consumes one credit. Free accounts receive 50 credits per month; paid accounts receive more as described on the Pricing page.",
      "Unused free-plan credits do not roll over to the next month. Unused paid-plan credits roll over for up to 12 months.",
      "We reserve the right to adjust credit allotments and usage limits with reasonable advance notice.",
    ],
  },
  {
    id: "disclaimer",
    title: "8. Disclaimer",
    body: [
      "The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, express or implied.",
      "We do not guarantee that the Service will be uninterrupted, error-free, or that puzzles will meet your specific educational requirements.",
      "You use puzzles generated by this tool at your own discretion. We are not liable for the content of puzzles you create.",
    ],
  },
  {
    id: "liability",
    title: "9. Limitation of Liability",
    body: [
      "To the maximum extent permitted by law, Word Puzzle Generator shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of data, profits, or goodwill, arising out of your use of the Service.",
    ],
  },
  {
    id: "termination",
    title: "10. Termination",
    body: [
      "You may delete your account at any time by contacting us.",
      "We may suspend or terminate your access to the Service if you violate these Terms, or if we discontinue the Service or any part of it.",
      "Upon termination, your saved puzzles may be deleted after a 30-day grace period.",
    ],
  },
  {
    id: "changes",
    title: "11. Changes to These Terms",
    body: [
      "We may update these Terms from time to time. When we do, we will update the 'last updated' date at the top of this page and notify users of significant changes via email.",
      "Continued use of the Service after changes take effect constitutes acceptance of the new Terms.",
    ],
  },
  {
    id: "contact",
    title: "12. Contact Us",
    body: [
      "If you have questions about these Terms, please contact us:",
      "Email: hello@wordpuzzlegenerator.example",
    ],
  },
]

export default function TermsPage() {
  return (
    <PageLayout>
      <section className="relative overflow-hidden border-b border-border bg-gradient-to-b from-primary-light/40 to-background">
        <div className="container-app py-16 md:py-20">
          <div className="mx-auto max-w-3xl text-center">
            <span className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-background px-4 py-1.5 text-sm font-medium text-primary shadow-sm">
              <FileText className="h-4 w-4" />
              Last updated: August 6, 2026
            </span>
            <h1 className="mt-6 text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Terms of Service
            </h1>
            <p className="mt-6 text-lg text-muted-foreground md:text-xl">
              The rules of the road for using Word Puzzle Generator. Please read
              them — they protect both you and us.
            </p>
          </div>
        </div>
      </section>

      <section className="py-16">
        <div className="container-app">
          <div className="mx-auto max-w-3xl space-y-10">
            <p className="text-base leading-relaxed text-muted-foreground">
              Welcome to Word Puzzle Generator. By using our website and
              services, you agree to the following terms. We have tried to write
              them in plain English rather than legalese — if anything is
              unclear, please reach out.
            </p>

            {SECTIONS.map((section) => (
              <div key={section.id} id={section.id} className="scroll-mt-20">
                <h2 className="text-2xl font-bold tracking-tight text-foreground">
                  {section.title}
                </h2>
                <div className="mt-4 space-y-3">
                  {section.body.map((para, idx) => (
                    <p
                      key={idx}
                      className={
                        idx === 0 || para.startsWith("Email:")
                          ? "text-base leading-relaxed text-muted-foreground"
                          : "ml-4 text-base leading-relaxed text-muted-foreground before:content-['•'] before:mr-2 before:text-secondary"
                      }
                      dangerouslySetInnerHTML={{ __html: para }}
                    />
                  ))}
                </div>
              </div>
            ))}

            <div className="rounded-2xl border border-border bg-muted/30 p-8 text-center">
              <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground">
                <Mail className="h-6 w-6" />
              </div>
              <h2 className="text-xl font-bold text-foreground">
                Questions about these terms?
              </h2>
              <p className="mt-2 text-sm text-muted-foreground">
                We are happy to clarify anything in these terms.
              </p>
              <Button asChild className="mt-5">
                <a href="mailto:hello@wordpuzzlegenerator.example">
                  Contact Us
                </a>
              </Button>
            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  )
}
